apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
    app: server-service
spec:

  selector:
    tier: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      